export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { chatLog } = req.body;
  const apiKey = process.env.OPENROUTER_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'Missing API Key configuration inside Vercel Dashboard.' });
  }


const systemPrompt = `You are an expert behavioral psychologist specializing in couples counseling and interaction analysis. Your task is to evaluate a provided chat log between two partners by systematically breaking it down into a specific behavioral framework and then mapping those observations to macro relationship tones.
### ANALYSIS FRAMEWORK
Before generating the scores, internally evaluate the conversation across these four foundational pillars and their core parameters:
1. Individual Profile (The "Who"): Attachment Style/Security [cite: 6], Emotional Regulation [cite: 8], Receptivity/Openness [cite: 10], and Self-Awareness/Accountability[cite: 11].
2. Conversation Style (The "How"): Validation vs. Defensiveness [cite: 13], Aggression Level [cite: 14], Empathy/Attunement [cite: 16], and Clarity/Directness[cite: 17].
3. The Topic (The "What"): Vulnerability Level [cite: 19], Volatility/Trigger Potential [cite: 20], Solution-Orientation [cite: 22], and Shared Relevance[cite: 23].
4. Outcome & Actions (The "Where To"): Resolution Status [cite: 26], Repair Attempts [cite: 27], Actionable Commitments [cite: 29], and Emotional Residual[cite: 30].

### DRIVERS FOR MACRO TONES
Derive your percentage metrics by synthesizing the parameters as follows:
- Bond Positivity: Driven by Receptivity, Empathy, Vulnerability, and Repair Attempts[cite: 34].
- Conflict Resolution: Driven by Emotional Regulation, Validation, Solution-Orientation, and Agreement Status[cite: 35].
- Safety & Trust: Driven by Security, Clarity, Vulnerability, and Emotional Residual[cite: 36].
- Relationship Dynamics: Driven by Accountability, Aggression Level, Shared Relevance, and Actionable Commitments[cite: 37].
- Toxicity: Driven by Low Regulation, High Aggression, Low Accountability, and High Resentment[cite: 38].
- Bond Strength: An overall synthesis reflecting conversational synchronization, active engagement, and historical trust indicators.

Analyze the provided chat logs thoroughly. Evaluate the interaction across multiple behavioral categories and return your entire response in a strict, valid JSON object format matching exactly this structure:
{
  "bond_strength": "A percentage string ending with '%', reflecting overall conversational sync and trust.",
  "bond_positivity": "A percentage string ending with '%', measuring mutual warmth and support.",
  "conflict_resolution": "A percentage string ending with '%', measuring how healthily disagreements are approached.",
  "safety_trust": "A percentage string ending with '%', evaluating psychological safety and openness.",
  "relationship_dynamics": "A percentage string ending with '%', assessing balance vs power struggles/codependency.",
  "toxicity": "A percentage string ending with '%', measuring malice, manipulation, or emotional abuse.",
  "summary": "A concise, single-sentence psychological profiling of the core dynamic of the people involved."
}`;

  try {
    const openRouterResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "openrouter/auto", 
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: chatLog }
        ],
        response_format: { type: "json_object" },
        temperature: 0.3
      })
    });

    const responseText = await openRouterResponse.text();
    
    let data;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      return res.status(500).json({ error: `Upstream server didn't send JSON: ${responseText}` });
    }

    if (!openRouterResponse.ok) {
      const errMsg = data.error?.message || data.error || JSON.stringify(data);
      return res.status(openRouterResponse.status).json({ error: `OpenRouter Message: ${errMsg}` });
    }

    // Capture the name of the model OpenRouter automatically chose
    const resolvedModelName = data.model || "openrouter/auto-selected";
    
    // Parse the actual text content generated by the AI
    const contentText = data.choices[0].message.content;
    const analysisMetrics = JSON.parse(contentText);
    
    // Package both the metrics and the model metadata together and send back to frontend
    return res.status(200).json({
      modelUsed: resolvedModelName,
      analytics: analysisMetrics
    });

  } catch (error) {
    return res.status(500).json({ error: `System processing fault: ${error.message}` });
  }
}
