export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { chatLog } = req.body;
  const apiKey = process.env.OPENROUTER_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'Missing API Key configuration inside Vercel Dashboard.' });
  }

  const systemPrompt = `You are an expert behavioral psychologist. Analyze the provided chat logs thoroughly.
  Evaluate the interaction across multiple behavioral categories and return your entire response in a strict, valid JSON object format matching exactly this structure:
  {
    "bond_strength": "A percentage string ending with '%', reflecting overall conversational sync and trust.",
    "bond_positivity": "A percentage string ending with '%', measuring mutual warmth and support.",
    "conflict_resolution": "A percentage string ending with '%', measuring how healthily disagreements are approached.",
    "safety_trust": "A percentage string ending with '%', evaluating psychological safety and openness.",
    "relationship_dynamics": "A percentage string ending with '%', assessing balance vs power struggles/codependency.",
    "toxicity": "A percentage string ending with '%', measuring malice, manipulation, or emotional abuse.",
    "summary": "A concise, single-sentence psychological profiling of the core dynamic of the people involved."
  }`;

  try {
    const openRouterResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "openrouter/auto", 
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: chatLog }
        ],
        response_format: { type: "json_object" },
        temperature: 0.3
      })
    });

    const responseText = await openRouterResponse.text();
    
    let data;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      return res.status(500).json({ error: `Upstream server didn't send JSON: ${responseText}` });
    }

    if (!openRouterResponse.ok) {
      const errMsg = data.error?.message || data.error || JSON.stringify(data);
      return res.status(openRouterResponse.status).json({ error: `OpenRouter Message: ${errMsg}` });
    }

    // Capture the name of the model OpenRouter automatically chose
    const resolvedModelName = data.model || "openrouter/auto-selected";
    
    // Parse the actual text content generated by the AI
    const contentText = data.choices[0].message.content;
    const analysisMetrics = JSON.parse(contentText);
    
    // Package both the metrics and the model metadata together and send back to frontend
    return res.status(200).json({
      modelUsed: resolvedModelName,
      analytics: analysisMetrics
    });

  } catch (error) {
    return res.status(500).json({ error: `System processing fault: ${error.message}` });
  }
}
